### ISSUE TITLE
Couldn't load plugin 'ordered_relation_editor' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/qgis-ordered-relation-editor#12]
Hi, I am having this issue/error when installing the plugin (version 0.2.8).
For the details of my installation, see second printscreen.
Any workaround or solution for this?
Thank you

![image](https://github.com/opengisch/qgis-ordered-relation-editor/assets/57868975/505a6a79-5eee-462e-9f3c-142669301da0)
![image](https://github.com/opengisch/qgis-ordered-relation-editor/assets/57868975/e54e0e6c-a89c-45d4-aef8-5270fdf97c95)

**Comment by domi4484** [comment]
Hi, probably you don't have the package `python3-pyqt5.qtquick` installed on your Ubuntu. Installing it should solve the issue:
```bash
sudo apt install python3-pyqt5.qtquick
```

**Comment by BoswachterMarc** [comment]
Thank you @domi4484 
This issue is solved.
